config:
  aws:region: us-west-1
  pulumi:template: aws-python

  fargate_container:cpu: 256
  fargate_container:memory: 512
  fargate_container:replicas: 1
  fargate_container:vpc: vpc-f3cfaa97
  fargate_container:subnet: subnet-f599aa91
