name: dev deployment
on:
  push:
    branches:
      - main

env:
  DEPLOY_ENV: "dev"
  AWS_DEFAULT_REGION: "us-east-1"
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID_DEV }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN_DEV }}
  DB_USERNAME: ${{ secrets.DB_USERNAME_DEV }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD_DEV }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rlespinasse/github-slug-action@v4
      - name: docker build and publish
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: aws-data-migration-${{ env.DEPLOY_ENV }}
          tags: ${{ env.GITHUB_REF_SLUG_URL }}-${{ env.GITHUB_SHA_SHORT }}
          dockerfile: src/Dockerfile
          buildArgs: SRC_DIR=src
          registry: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs:
      - build
    defaults:
      run:
        working-directory: ./infra
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install -r requirements.txt
      - uses: rlespinasse/github-slug-action@v4
      - name: pulumi up
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: ${{ env.DEPLOY_ENV }}
          work-dir: ./infra
        env:
          DOCKER_HOST: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com
          DOCKER_IMAGE_TAG: ${{ env.GITHUB_REF_SLUG_URL }}-${{ env.GITHUB_SHA_SHORT }}