name: prod deployment
on:
  push:
    branches:
      - main_prod

env:
  DEPLOY_ENV: "prod"
  AWS_DEFAULT_REGION: "ca-central-1"
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID_PROD }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN_PROD }}
  DB_USERNAME: ${{ secrets.DB_USERNAME_PROD }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD_PROD }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: rlespinasse/github-slug-action@v4
      - name: docker build and publish
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: brell-infra-${{ env.DEPLOY_ENV }}-api
          tags: ${{ env.GITHUB_REF_SLUG_URL }}-${{ env.GITHUB_SHA_SHORT }}
          dockerfile: server/Dockerfile
          buildArgs: SRC_DIR=server
          registry: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs:
      - build
    defaults:
      run:
        working-directory: ./infra
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install -r requirements.txt
      - uses: rlespinasse/github-slug-action@v4
      - name: pulumi up
        uses: pulumi/actions@v3
        with:
          command: up
          stack-name: ${{ env.DEPLOY_ENV }}
          work-dir: ./infra
        env:
          DOCKER_IMAGE_TAG: ${{ env.GITHUB_REF_SLUG_URL }}-${{ env.GITHUB_SHA_SHORT }}